import type { Metadata } from "next";
import "./styles/scss/app.scss";
import Header from "./(Pages)/components/Header";
import { IBMPlexMonoFont } from "./styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={IBMPlexMonoFont.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
